package es.unican.ps.supermercado.web;

// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
public class RealizarPedidoTest {
	private WebDriver driver;
	private Map<String, Object> vars;
	JavascriptExecutor js;
	@Before
	public void setUp() {
		System.setProperty("webdriver.chrome.driver", "C:\\Escritorio\\4_CURSO\\PROCESOS_SOFTWARE\\Recursos\\chromedriver__win32\\chromedriver.exe");
		driver = new ChromeDriver();
		js = (JavascriptExecutor) driver;
		vars = new HashMap<String, Object>();
	}
	@After
	public void tearDown() {
		driver.quit();
	}
	@Test
	public void realizarPedido() {
		driver.get("http://localhost:8080/SupermercadoWeb/login.jsf");
		driver.manage().window().setSize(new Dimension(1552, 840));
		assertThat(driver.findElement(By.cssSelector("h1")).getText(), is("Mi Supermercado"));
		assertThat(driver.findElement(By.cssSelector("label")).getText(), is("DNI:"));
		driver.findElement(By.name("j_idt6:j_idt9")).click();
		driver.findElement(By.name("j_idt6:j_idt9")).sendKeys("12345678A");
		driver.findElement(By.id("j_idt6:buttonEntrar")).click();
		assertThat(driver.findElement(By.cssSelector("h1")).getText(), is("Artículos"));
		assertThat(driver.findElement(By.cssSelector("th:nth-child(1)")).getText(), is("Nombre"));
		assertThat(driver.findElement(By.cssSelector("th:nth-child(2)")).getText(), is("Precio"));
		driver.findElement(By.id("j_idt6:j_idt7:3:anhadir-carrito-id")).click();
		driver.findElement(By.name("j_idt6:j_idt11")).click();
		driver.findElement(By.name("j_idt6:j_idt11")).sendKeys("2");
		driver.findElement(By.id("j_idt6:buttonAnhadirCarro")).click();
		assertThat(driver.findElement(By.cssSelector("h1")).getText(), is("Artículo Seleccionado"));
		assertThat(driver.findElement(By.cssSelector("tr:nth-child(1) > td:nth-child(1) > label")).getText(), is("Artículo:"));
		assertThat(driver.findElement(By.cssSelector("tr:nth-child(2) label")).getText(), is("Unidades:"));
		driver.findElement(By.id("j_idt6:buttonVolver")).click();
		driver.findElement(By.id("j_idt6:buttonVerCarrito")).click();
		assertThat(driver.findElement(By.cssSelector("h1")).getText(), is("Carro Compra"));
		assertThat(driver.findElement(By.cssSelector("th:nth-child(1)")).getText(), is("Nombre"));
		assertThat(driver.findElement(By.cssSelector("th:nth-child(2)")).getText(), is("Unidades"));
		assertThat(driver.findElement(By.cssSelector("tr:nth-child(1) label")).getText(), is("Precio:"));
		assertThat(driver.findElement(By.cssSelector("tr:nth-child(2) label")).getText(), is("Hora de recogida:"));
		driver.findElement(By.name("j_idt6:j_idt18")).click();
		driver.findElement(By.name("j_idt6:j_idt18")).sendKeys("20:00:00");
		driver.findElement(By.id("j_idt6:buttonConfirmarCarro")).click();
		assertThat(driver.findElement(By.cssSelector("h1")).getText(), is("Pedido Realizado"));
		assertThat(driver.findElement(By.cssSelector("tr:nth-child(1) > td:nth-child(1) > label")).getText(), is("Referencia:"));
		assertThat(driver.findElement(By.cssSelector("tr:nth-child(2) label")).getText(), is("Precio:"));
		assertThat(driver.findElement(By.cssSelector("tr:nth-child(3) label")).getText(), is("Hora recogida:"));
	}
}
